apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-11-05T18:08:28Z"
  labels:
    app: events-api
  name: events-api-svc
  namespace: default
  resourceVersion: "6867"
  uid: 43d6d059-27ac-4eb8-9338-fc4866e26148
spec:
  clusterIP: 10.99.171.173
  clusterIPs:
  - 10.99.171.173
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: events-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
